_SCHEMAS = [
    "create-transactions-request",
    "create-transactions-response",
    "export-transactions-response",
    "get-transactions-request",
    "get-transactions-response",
    "list-accounts-request",
    "list-accounts-response",
]

_PKG = "com/moneydance/modules/features/moneylens/schema"

genrule(
    name = "json_schema_files",
    srcs = ["//schema:{}.schema.json".format(s) for s in _SCHEMAS],
    outs = ["{}/{}.schema.json".format(_PKG, s) for s in _SCHEMAS],
    cmd = "mkdir -p $(RULEDIR)/{pkg} && cp $(SRCS) $(RULEDIR)/{pkg}/".format(pkg = _PKG),
)

filegroup(
    name = "resources",
    srcs = [
        "meta_info.dict",
        ":json_schema_files",
    ],
    visibility = ["//moneydance:__subpackages__"],
)
