load("@rules_java//java:defs.bzl", "java_binary")
load("@rules_java//java:java_single_jar.bzl", "java_single_jar")

java_binary(
    name = "key_admin",
    main_class = "com.moneydance.admin.KeyAdmin",
    runtime_deps = ["@moneydance_devkit//:lib"],
)

# This target represents the environment that the :moneylens plugin gets
# deployed into, like Moneydance's internals that we compile against.
# This gets excluded from the plugin bundle in the :moneylens target.
java_single_jar(
    name = "moneydance_runtime",
    deps = [
        "@moneydance_devkit//:lib",
        # Moneydance 5253 ships with Kotlin stdlib & reflect 1.9.21
        "@maven//:org_jetbrains_kotlin_kotlin_reflect",
        "@rules_kotlin//kotlin/compiler:kotlin-stdlib",
        # Moneydance 5253 ships with jackson-core 2.17.0
        "@maven//:com_fasterxml_jackson_core_jackson_core",
    ],
)

java_single_jar(
    name = "moneylens",
    deploy_env = [":moneydance_runtime"],
    visibility = ["//visibility:public"],
    deps = ["//moneydance/src/main/kotlin:moneylens_lib"],
)

genrule(
    name = "moneylens_mxt",
    srcs = [
        "moneylens.jar",
        ":test-private-key",
    ],
    outs = ["moneylens.mxt"],
    cmd = """
        $(location :key_admin) signextjar \
            $(location :test-private-key) \
            99 \
            moneylens \
            $(location :moneylens.jar) 2>/dev/null

        mv s-moneylens.mxt $@
    """,
    tools = [":key_admin"],
)
